# Generated by Django 3.0.6 on 2020-09-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200902_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[('1', 'pub'), ('2', 'booth'), ('3', 'performance'), ('4', 'etc')], null=True),
        ),
    ]
