# Generated by Django 3.0.6 on 2020-09-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'pub'), ('2', 'booth'), ('3', 'performance'), ('4', 'etc')], max_length=300, null=True),
        ),
    ]
