# Generated by Django 3.0.6 on 2020-09-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200915_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_user_set',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('주', '점'), ('부', '스'), ('공', '연'), ('기', '타')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
