# Generated by Django 3.0.6 on 2020-09-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200915_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[('주', '점'), ('부', '스'), ('공', '연'), ('기', '타')], max_length=300, null=True),
        ),
    ]
