# Generated by Django 3.0.6 on 2020-09-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200915_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('pub', '주점'), ('booth', '부스'), ('performance', '공연'), ('etc', '기타')], max_length=300, null=True),
        ),
    ]
